### ISSUE TITLE
[Design] Create design visuals to support the 5.1.2 release

### ISSUE THREAD

**Issue by RCheesley** [mautic/low-no-code#42]
In October we'll be making the 5.1.2 release.

The release is called 'Mirach' after the star in the Andromeda constellation - our release themes are all based on constellations, with patch releases within them being stars from that constellation.

Our previous releases have been Andromeda (5.1) and Alpheratz (5.1.1).

Here you can see the designs we used for Andromeda: https://www.canva.com/design/DAGH6tZ_wf4/CrUNbua6gkkGX75zxm6F5w/edit
https://www.facebook.com/MauticCommunity/posts/pfbid02a3K6E8MiNBkWAyTLxnHSR88t8Yp9fZQ8VEbfFnhqh1dtKCbiY4QkC8NyqZvLoRgDl

It'd be great to create something along these lines for Mirach, so we can retain some consistency between releases. It doens't need to be so extensive in listing things included, because a patch release like this doesn't include new features, only bug fixes. This will also be a security release so we may wish to factor that in.

Let us know if you need an invitation to Canva. We'll need the following sizes (you can use magic resize in Canva):

- Facebook
- Twitter
- Instagram (portrait)
- Instagram (story)
- LinkedIn
- Threads
- Mastodon

**Comment by miracle-E** [comment]
@RCheesley I'd like to work on this too

**Comment by RCheesley** [comment]
@miracle-E  please go ahead!

**Comment by RCheesley** [comment]
Closing this task as we've now released 5.2.0.
