### ISSUE TITLE
[Design] Create visual imagery to support the 5.2.0 release

### ISSUE THREAD

**Issue by RCheesley** [mautic/low-no-code#43]
In October we'll be making the Release Candidate release for Mautic 5.2.

The release is called 'Pleiades (pronounced 'Ply-a-dees') after the star constellation - our release themes are all based on constellations, with patch releases within them being stars from that constellation.

Our last releases have been Andromeda (5.1) and Alpheratz (5.1.1). Mirach (5.1.2) and Orion (6.0-alpha) will be released on the same day.

Here you can see the designs we used for Andromeda: https://www.canva.com/design/DAGH6tZ_wf4/CrUNbua6gkkGX75zxm6F5w/edit
https://www.facebook.com/MauticCommunity/posts/pfbid02a3K6E8MiNBkWAyTLxnHSR88t8Yp9fZQ8VEbfFnhqh1dtKCbiY4QkC8NyqZvLoRgDl

It'd be great to create something along these lines for Pleiades, so we can retain some consistency between releases.

Let us know if you need an invitation to Canva. We'll need the following sizes (you can use magic resize in Canva):

- Blog image (720x33px)
- Facebook
- Twitter
- Instagram (portrait)
- Instagram (story)
- LinkedIn
- Threads
- Mastodon

You can work with the person writing up the blog post announcement on the content.

**Comment by EfeAkhigbe** [comment]
Please, I would like to work on this  @RCheesley

**Comment by RCheesley** [comment]
Sure @EfeAkhigbe - all the info you need should be in the post above. We're going to be making this release in a week's time. Let us know your email address on Slack and we can add you to Canva.

**Comment by RCheesley** [comment]
https://github.com/mautic/mautic/pulls?q=is%3Apr+milestone%3A5.2+is%3Amerged+sort%3Aupdated-asc+ here is a list of what has been merged in Mautic - you should also liaise with @TusharGupta-Developer who is working on the content in #44 - as your imagery will need to highlight the content that they're writing in the blog post announcement.

**Comment by EfeAkhigbe** [comment]
Ok, thank you.

**Comment by RCheesley** [comment]
Thanks @EfeAkhigbe for your awesome work on this! 🚀
